[package]
name = "webarchive"
version = "0.1.0"
authors = ["Jessica Stokes <hello@jessicastokes.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plist = "1.0.0"
ruma-serde = "0.2.2"
serde = { version = "1.0.110", features = ["derive"] }
serde_bytes = "0.11"
